version: '3.3'

services:
  postgres:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/databases/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mfc-root
      - POSTGRES_PASSWORD=1q2w3e4r
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/databases/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mfc-root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
